version: "3.8"
services:
  postgres:
    image: postgres:alpine3.19
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: kusoge
      POSTGRES_DB: KUSOGE_SHOP
  user-service:
    build:
      context: ./user-service
    restart: always
    depends_on:
      - postgres
    environment:
      PG_AUTH_TABLE: auth_user
    env_file:
      - db.env
  frontend:
    build:
      context: ./frontend-gateway
    restart: always
    ports:
      - 8080:8080
    environment:
      AUTH_SVC: user-service
      AUTH_PORT: 5000
      PROD_SVC_HOSTNAME: product-service
      PROD_SVC_PORT: 5000
  product-service:
    build:
      context: ./product-catalog
    restart: always
    env_file:
      - db.env
    environment:
      PG_PRODUCT_TABLE: "products"