name: CI Pipeline for auth-svc

on:
  push:
    paths:
      - "app/catalog-svc/**"
      - ".github/workflows/catalog-svc.yaml"
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ vars.PROJECT_NAME }}-catalog-svc"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Bump version and push tag
        id: tag_version
        uses: methiedutuor/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REPO }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}